### ISSUE TITLE
Bugged armor

### ISSUE THREAD

**Issue by CyberSteve777** [nu11une/wardenloot#4]
![2022-06-27_00 06 59](https://user-images.githubusercontent.com/69720241/175833939-450bca9b-6d14-4852-ba8b-e65ed365ddba.png)

**Comment by nu11une** [comment]
Instructions to reproduce this bug? Is this with other mods installed or only Warden Loot and its dependencies? It looks like the armor animation - which is handled by MoreMcmeta - is failing, so make sure you have MoreMcmeta installed and up-to-date.

**Comment by CyberSteve777** [comment]
I just installed mod and put up the armor. Here goes my mod list. I thought it could be because of Essential, but when I disabled it,  nothing changed
![image](https://user-images.githubusercontent.com/69720241/175903217-71f5aaa3-887a-4263-9b27-cb22c2853fcb.png)

**Comment by nu11une** [comment]
Looks like the issue is an incompatibility between LambDynamicLights and MoreMcmeta. I'll publish a new release later with a temporary fix, and then I'll open an issue with MoreMcmeta to hopefully get the incompatibility resolved.

**Comment by nu11une** [comment]
Fix has been released 👍 https://www.curseforge.com/minecraft/mc-mods/warden-loot/files/3850110

**Comment by CyberSteve777** [comment]
nice👍

**Comment by CyberSteve777** [comment]
Uhh, the issue still appear
![2022-06-27_17 30 31](https://user-images.githubusercontent.com/69720241/175966668-75c9fc71-b3bf-4efa-a7f8-144f3c11e589.png)

**Comment by CyberSteve777** [comment]
@nu11une needs reopening

**Comment by nu11une** [comment]
🤦 stupid mistake on my part. Actual fix will be here as soon as the file gets approved -> https://www.curseforge.com/minecraft/mc-mods/warden-loot/files/3851274

**Comment by SniffSniff125** [comment]
i have the same problem, but im not using optifine nor dynamic lights, just rubidium (forge sodium)
